services:
  db:
    image: postgres:15
    container_name: bookshop_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookshop_network

  backend:
    image: ${REGISTRY_IMAGE}:${IMAGE_TAG}
    container_name: bookshop_backend
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    depends_on:
      - db
    ports:
      - "${HOST_PORT:-8000}:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - bookshop_network

volumes:
  postgres_data:

networks:
  bookshop_network:
    driver: bridge
